POST https://ecshopvietnam.com/ecshopstore/callback_payment?code=vietqr_quick
Content-Type: application/json
secure-token: eogrBiWqaq

{
    "error": 0,
    "data": [
        {
            "id" : 1, 
            "when": "2020-11-02 11:50:30",
            "amount": 310000,
            "description": "DH2024101150386L345",
            "cusum_balance": 0,
            "tid": "TF80307914",
            "subAccId": "123456789",
            "bank_sub_acc_id": "123456789",
            "virtualAccount": "",
            "virtualAccountName": "",
            "corresponsiveName": "",
            "corresponsiveAccount": "",
            "corresponsiveBankId": "",
            "corresponsiveBankName": ""
        }
    ]
}